- name: check arch & do some action 
  hosts: localhost
  connection: local
  gather_facts: True 
  tasks: 
   - command: cat /etc/os-release
     register: out
   - debug: var=out.stdout
     when: ansible_distribution == 'SLES'
   - command: echo "hello"
     register: out
   - debug: var=out.stdout
     when: ansible_distribution == 'Redhat'
   - command: cat /etc/os-release
     register: out
   - debug: var=out.stdout_lines[Name]
     when: ansible_distribution == 'Ubuntu'
