- hosts: all
  tasks:
    - set_fact:
        SERVICE: httpd
      when: ansible_distribution == 'RedHat'

    - set_fact:
        SERVICE: apache2
      when: ansible_distribution == 'Ubuntu'

    - debug:
        msg: "SERVICE = {{SERVICE}}"
