---

  - name: "Check Kernel Version"
    shell: cat /etc/os-release;uname -a;ps -ef | grep java | grep -v grep| wc -l;echo ' ';
    register: outputsuse
     
  - file: path=/tmp/osrelease_output_suse.log state=touch mode=0777 owner=root group=root
  
  - copy:
     content: "{% for host in groups.suse %}{{ hostvars[host].outputsuse.stdout }}\n{% endfor %}"
     dest: /tmp/osrelease_output_suse.log
    delegate_to: localhost
    when: outputsuse is defined
