---
- name: uninstall|Stopped and disabled tomcat service
  service:
    name: '{{ tomcat_service_name }}'
    enabled: no
    state: stopped
  ignore_errors: yes
  register: service_result
  failure_when: "service_result.failed == true and not 'rc: 0' in service_result.msg"  

- name: sleep for 60 seconds to make sure services stop cleanly
  wait_for: timeout=60
  delegate_to: localhost

- name: process check
  shell: ps -ef | grep java | wc -l
  register: java_cnt
- 
 debug: var=java_cnt.stdout
 
- name: Kill Process
  shell: killall -9 java
  when: java_cnt.stdout>1
  ignore_errors: yes
   

- name: uninstall|Delete tomcat folder
  file:
    path: '{{ item.path }}'
    state: absent
  with_items:
    - { path: '{{ root_dir }}/tomcatprofile' }
    - { path: '/home/tomcatprofile' }
    - { path: '/opt/sun' }
    - { path: '/opt/apache' }
    - { path: '/opt/java' }
    - { path: '/opt/tomcat' }
    - { path: '/opt/ant' }
    - { path: '/etc/init.d/tomcatd' }
  ignore_errors: yes 